name: deploy

on:
  push:
    branches:
      - master

jobs:
  back:
    name: deploy back, api and client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: deploy back
      uses: akhileshns/heroku-deploy@v3.8.9
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: itmo-software-testing
        heroku_email: daretoodefy@gmail.com
        appdir: back
        buildpack: heorku/gradle
        procfile: "web: java -jar build/libs/software-testing-0.1.0-SNAPSHOT.jar --server.port=$PORT"
        healthcheck: https://itmo-software-testing.herokuapp.com/health
        delay: 40
        checkstring: OK
        rollbackonhealthcheckfailed: true
      env:
        HD_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        HD_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        HD_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

    - name: deploy api
      uses: akhileshns/heroku-deploy@v3.8.9
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: itmo-software-testing-api
        heroku_email: daretoodefy@gmail.com
        appdir: api
        buildpack: heorku/nodejs

    - name: deploy client
      uses: akhileshns/heroku-deploy@v3.8.9
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: itmo-software-testing-client
        heroku_email: daretoodefy@gmail.com
        appdir: client
        buildpack: heorku/nodejs
        healthcheck: https://itmo-software-testing-client.herokuapp.com/
        delay: 20
        rollbackonhealthcheckfailed: true
      env:
        HD_REACT_APP_BACK_URL: https://itmo-software-testing.herokuapp.com/
        HD_REACT_APP_API_URL: https://itmo-software-testing-api.herokuapp.com/
