name: lint

on: [push]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      working-directory: client
      run: npm install
    - name: install eslint
      run: npm install eslint
    - name: linter
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: client/src
