name: test back

on: [push]

jobs:
  npm:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: test
      working-directory: ./back
      run: ./gradlew test
