name: test

on: [push]

jobs:
  npm:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm install
      working-directory: ./client
      run: npm install
    - name: test
      working-directory: ./client
      run: npm test
